name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use the node version compatible with your app

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend # Adjust if your frontend is in a different folder

      - name: Build project
        run: npm run build
        working-directory: ./frontend # Adjust if your frontend is in a different folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist  # Adjust if the frontend folder structure is different
          keep_files: false  # Clears any previously existing files in gh-pages
